name: Tests

on: push

jobs:
  phpunit:
    name: PHP Test
    uses: XNXKTech/workflows/.github/workflows/php-test.yml@main
    with:
      versions: "[\"8.0\", \"8.1\"]"
      stability: "[\"prefer-stable\"]"
      env: |
        DEBUG: true
        ESIGN_SERVER: https://openapi.esign.cn
        ESIGN_APPID: ${{ secrets.ESIGN_APPID }}
        ESIGN_APPKEY: ${{ secrets.ESIGN_APPKEY }}